# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np

## Importing the dataset

In [5]:
dataset = pd.read_csv('Social_Network_Ads.csv')
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values
print(x[0:5])
print(y[0:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
[0 0 0 0 0]


## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
(x_train, x_test, y_train, y_test)=train_test_split(x, y, test_size=0.2, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 2)
(80, 2)
(320,)
(80,)


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
print(x_train[0:5])
print(x_test[0:5])

[[ 1.92295008  2.14601566]
 [ 2.02016082  0.3787193 ]
 [-1.3822153  -0.4324987 ]
 [-1.18779381 -1.01194013]
 [ 1.92295008 -0.92502392]]
[[-0.79895082  0.49460758]
 [-0.02126485 -0.57735906]
 [-0.31289709  0.14694273]
 [-0.79895082  0.26283101]
 [-0.31289709 -0.57735906]]


## Training the K-NN model on the Training set

In [12]:
from sklearn.neighbors import KNeighborsClassifier
# default for n_neighbors is 5

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predicting a new result

In [14]:
sampleVal = classifier.predict([[35, 88000]])
print(sampleVal)

[1]


## Predicting the Test set results

In [19]:
# y_test was already scaled
y_pred = classifier.predict(x_test)

In [24]:
print(y_pred[10:25])
print(y_test[10:25])

[0 0 0 0 0 1 0 0 1 0 0 1 0 1 0]
[0 0 0 0 0 0 0 0 1 0 0 1 0 1 0]


## Making the Confusion Matrix

## Visualising the Training set results

## Visualising the Test set results