
# Breast Cancer Classifier
### from 'Breast Cancer Wisconsin (Original) Data Set'


## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [7]:
dataset = pd.read_csv('breast_cancer.csv')
x = dataset.iloc[: , 1:-1].values
y = dataset.iloc[: , -1].values
print(x[0:5])
print(y[0:5])
# Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
# Classification: benign=2, malignant=4
# no missing data here

[[ 5  1  1  1  2  1  3  1  1]
 [ 5  4  4  5  7 10  3  2  1]
 [ 3  1  1  1  2  2  3  1  1]
 [ 6  8  8  1  3  4  3  7  1]
 [ 4  1  1  3  2  1  3  1  1]]
[2 2 2 2 2]


## Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
(x_train, x_test, y_train, y_test) = train_test_split(x, y, test_size=0.20, random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(546, 9)
(137, 9)
(546,)
(137,)


## Training the Logistic Regression model on the Training set

## Predicting the Test set results

## Making the Confusion Matrix

## Computing the accuracy with k-Fold Cross Validation